name: code-scan

on:
  push:
    branches:
      - main
      - development

jobs:
  analyze:
    name: Code-Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          # Analyzes C++ code.
          - language: c-cpp
            build-mode: autobuild

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-extended,security-and-quality

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
