name: build-development

on:
  push:
    branches:
      - development_UI
    paths:
      - '4. Software/4.1 Quellen/**'

jobs:
  build:
    name: Build-Development
    runs-on: windows-latest
    timeout-minutes: 60
    permissions:
      security-events: none
      packages: read
      actions: read
      contents: write

    strategy:
      fail-fast: true
      matrix:
        include:
          - language: c-cpp
            build-mode: manual

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Install RaytRazor Project dependencies.
        shell: pwsh
        run: |
          Write-Host "Installing Chocolatey"
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          Write-Host "Refreshing environmental variables"
          refreshenv
          
          Write-Host "Installing dependencies using Chocolatey"
          choco install -y cmake make mingw

      - name: Generate Version Syntax
        shell: pwsh
        run: |
          $VERSION_FILE = "4. Software/4.1 Quellen/RaytRazor/VERSION.DAT"
          $BUILD_NUMBER = $env:GITHUB_RUN_NUMBER
          if (Test-Path $VERSION_FILE) {
            $VERSION = Get-Content $VERSION_FILE
          } else {
            $VERSION="0.0.0"
          }
          $VERSION_PARTS = $VERSION -split '\.'
          $MAJOR = $VERSION_PARTS[0]
          $MINOR = $VERSION_PARTS[1]
          $PATCH = $VERSION_PARTS[2]
          $BUILD = $VERSION_PARTS[3]
          $FULL_VERSION = "$MAJOR.$MINOR.$PATCH.$BUILD"
          Write-Host "Build version: $FULL_VERSION"
          "$FULL_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "$FULL_VERSION" | Out-File -FilePath $VERSION_FILE -Encoding utf8

      - name: Build RaytRazor Project
        shell: pwsh
        run: |
          Write-Host "Creating build directory"
          New-Item -ItemType Directory -Path build
          
          Write-Host "Moving to build directory"
          Set-Location build
          
          Write-Host "Building Project"
          cmake "../4. Software/4.1 Quellen/RaytRazor" -G "MinGW Makefiles"
          mingw32-make

      - name: Create release directory
        shell: pwsh
        run: |
          Write-Host "Creating release directory"
          New-Item -ItemType Directory -Path ../release
          
          Write-Host "Copying RaytRazor executable to release directory"
          Copy-Item "RaytRazor.exe" "../release/"
          
          Write-Host "Copying version file to release directory"
          Copy-Item "../4. Software/4.1 Quellen/RaytRazor/VERSION.DAT" "../release/VERSION.DAT"
          

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: RaytRazor-PreRelease-${{ env.version }}
          path: release/

  deploy:
    name: Deploy Pre-Release
    runs-on: windows-latest
    needs: build
    steps:
      - name: Create Pre-Release
        id: create_prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: RaytRazor-PreRelease-${{ env.version }}
          release_name: RaytRazor-PreRelease-${{ env.version }}
          draft: false
          prerelease: true

      - name: Upload Pre-Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_prerelease.output.upload_url }}
          asset_path: release/RaytRazor
          asset_name: RaytRazor-${{ env.version }}.exe
          asset_content_type: application/octet-stream
