name: code-scan

on:
  push:
    branches:
      - main
      - development
    paths:
      - '4. Software/4.1 Quellen/**'

jobs:
  analyze:
    name: Code-Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          # Analyzes C++ code.
          - language: c-cpp
            build-mode: manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Print current Position
        run: |
          pwd

      - name: List Checkout Directory/Files
        run: |
          ls -a

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake "./4. Software/4.1 Quellen/RaytRazor/"
          make

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-extended,security-and-quality

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
