name: code-scan

on:
  push:
    branches:
      - main
      - development
    paths:
      - '3. Software/3.1 Source/**'

jobs:
  analyze:
    name: Code-Analysis
    runs-on: windows-latest
    timeout-minutes: 60
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          # Analyzes C++ code.
          - language: c-cpp
            build-mode: manual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-extended,security-and-quality

      - name: Install RaytRazor Project dependencies.
        shell: pwsh
        run: |
          Write-Host "Installing Chocolatey"
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          Write-Host "Refreshing environmental variables"
          refreshenv
          
          Write-Host "Installing dependencies using Chocolatey"
          choco install -y cmake make mingw

      - if: ${{ matrix.build-mode == 'manual' }}
        name: Build C++ Code
        shell: pwsh
        run: |
          Write-Host "Creating build directory"
          New-Item -ItemType Directory -Path build
          
          Write-Host "Moving to build directory"
          Set-Location build
          
          Write-Host "Building Project"
          cmake "../3. Software/3.1 Source/RaytRazor" -G "MinGW Makefiles"
          mingw32-make
          
          Write-Host "Listing built folders/files"
          dir

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
